# Generated by Django 4.2.1 on 2023-11-16 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livre',
        ),
    ]
