# Generated by Django 4.2.1 on 2023-11-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
