# Generated by Django 4.2.1 on 2023-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='bouton_activer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='bouton_envoyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='bouton_separer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='led1_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='led2_state',
            field=models.BooleanField(default=False),
        ),
    ]
