# Generated by Django 4.2.1 on 2023-11-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0006_check_bouton_activer_check_bouton_envoyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='etat_checkbox',
        ),
        migrations.AlterField(
            model_name='check',
            name='led1_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='check',
            name='led2_state',
            field=models.IntegerField(default=0),
        ),
    ]
