# Generated by Django 4.2.1 on 2023-11-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prise', '0008_remove_check_led1_state_remove_check_led2_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
