# Generated by Django 4.2.1 on 2023-11-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prise', '0009_delete_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Led1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led1', models.BooleanField(default=False)),
            ],
        ),
    ]
